2016-06-16 10:49:21.094 -0600	START		Running Background.feature
2016-06-16 10:49:21.103 -0600	Log		20	3	on_i_have_num_apples	Background.script<SOURCE>
2016-06-16 10:49:21.106 -0600	Log		20	5	on_i_have_num_apples	Background.script<SOURCE>
2016-06-16 10:49:21.108 -0600	LogError		I have 20 apples
2016-06-16 10:49:21.108 -0600	Log		10	4	on_i_give_num_apples_to_a_monkey	Background.script<SOURCE>
2016-06-16 10:49:21.111 -0600	LogSuccess		I give 10 apples to a monkey
2016-06-16 10:49:21.112 -0600	Log		10	3	on_i_am_left_with_num_apples	Background.script<SOURCE>
2016-06-16 10:49:21.113 -0600	Log		success	8	on_i_am_left_with_num_apples	Background.script<SOURCE>
2016-06-16 10:49:21.115 -0600	LogSuccess		I am left with 10 apples
2016-06-16 10:49:21.116 -0600	EndTestCase		(Duration:"0.020084", Errors:"1", Exceptions:"0", StartTime:"2016-06-16 10:49:21 -0600", Successes:"2", TestCase:"Background.feature", Warnings:"0")
2016-06-16 10:49:21.122 -0600	FAILURE		1 scenarios (0 failed, 1 passed) 3 steps (0 failed, 0 skipped, 3 passed) Execution Time 0:00:00
