2016-06-20 14:42:16.160 -0600	START		Running Background1.feature
2016-06-20 14:42:16.167 -0600	Log		num	4	on_i_have_var_apples	Background1.script<SOURCE>
2016-06-20 14:42:16.169 -0600	LogSuccess		I have <num> apples
2016-06-20 14:42:16.184 -0600	LogError		i give <num> to mickey
2016-06-20 14:42:16.185 -0600	Log		f	7	on_i_am_left_with_var	Background1.script<SOURCE>
2016-06-20 14:42:16.187 -0600	LogSuccess		I am left with <num>
2016-06-20 14:42:16.188 -0600	EndTestCase		(Duration:"0.02669", Errors:"2", Exceptions:"0", StartTime:"2016-06-20 14:42:16 -0600", Successes:"2", TestCase:"Background1.feature", Warnings:"0")
2016-06-20 14:42:16.304 -0600	FAILURE	Screen_Error.png	1 scenarios (1 failed, 0 passed) 3 steps (1 failed, 0 skipped, 2 passed) Execution Time 0:00:00
